version: '3.1'
services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    ports:
    - "8888:8081"
  node:
    image: node:12
    volumes:
      - ./node:/code
    working_dir: /code
