version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: nosql-workshop-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
