version: '3.1'
services:
  mongo:
    image: mongo:4.2
    container_name: workshop_mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/tmp/data
  mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=workshop_mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_BASICAUTH_USERNAME=mongo-express
            - ME_CONFIG_BASICAUTH_PASSWORD=password
        depends_on:
            - mongo
        ports:
          - "8888:8081"
